---
deployment:
      tasks:
        - export DEPLOYPATH=/home/casidios/git-publish.casidios.com  # Add /<app_folder> if required
        - /bin/cp alpha.php $DEPLOYPATH                 #Copy specific file to destination from root
        - /bin/cp animando/commons.js $DEPLOYPATH   #copy specific file from source sub folder
        - /bin/cp * $DEPLOYPATH                           #copy all from root 
        - /bin/cp gravedad/* $DEPLOYPATH             #copy all from sub folder root
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        
